name: epatriote_smart_benin
description: Select Benin's location (Department, city or distreet) smartly from flutter.
version: 0.0.1-dev
homepage: https://github.com/ePatrioteCreative/epatriote_smart_benin
repository: https://github.com/ePatrioteCreative/epatriote_smart_benin.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
